
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()


title  Konceptuelt diagram over "Brugervendte dashboards"

Person(customer, "Ku ansat", "Ansatte på KU der bruger dashboards til at få overblik over data og statistikker.")
Enterprise_Boundary(c0, "KU IT", "Københavns Universitets IT-afdeling") {
System(isilon, "Isilon", "Storage til data")
System(Hdrives, "H-drev", "Storage til data")
System(zabbix, "Zabbix", "Monitorering af systemer")
System(fileshare, "Fileshare", "Deling af datafiler")




Enterprise_Boundary(c1, "Forkinngstøtte", "Forkningstøtte på KU") {
    System(dashdb, "Dash DB", "Database med data til dashboards")
    System(dashweb, "Dash WEB", "Brugervendte dashboards gui (grafana, django)")
    System(dashapp, "Dash APP", "API til dashboards")
}
}
Rel_U(customer, dashweb, "Bruger dashboards via")
Rel_D(isilon, fileshare, "sender data filer til")
Rel_D(Hdrives, fileshare, "sender data filer til")
Rel_U(fileshare, dashapp, "henter data fra")
Rel_Neighbor(zabbix, dashapp, "sender monitoreringsdata til")
Rel_U(dashapp, dashdb, "gemmer data i")
Rel_D(dashdb, dashweb, "henter data fra")

@enduml
