@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


title   KALM system

Person(kalmadmin, "Kalm system admin", "KALM system administrator")
Person(systemadmin, "System administrator", "OS system administrator")
Person(enduser, "Enduser", "Enduser of the system services")


Enterprise_Boundary(c0, "My Company", "My awesome organisation") {

Enterprise_Boundary(c2, "Server ", "Virtuelle servere") {
    System(vmware, "wmware", "Virtual servers running on wmware")
    System(physicalservers, "Physical", "Physical servers running on premise")
}

Enterprise_Boundary(c3, "Shared services", "Shared services in the organisation") {
    System(cmdb, "CMDB", "Configuration management database")
    System(automation, "Ansible", "Server configuration management")
    System(git, "Git", "Version control")
    System(monitorering, "Monitorering", "Monitorering services")
}

Enterprise_Boundary(c1, "automation services", "Automation services") {
    System(kalm, "KALM", "Knowit auitomation lifecycle management")
    System(kalmvisualize, "KALM-Visualize", "Knowit auitomation lifecycle management - visualize")
}


}


Rel_Neighbor(git, automation, "Read playbooks from git")
Rel_D(cmdb, automation, "Read inventory from cmdb")
Rel_U(automation, c2 , "execute playbooks on servers")


Rel_U(kalmadmin, git, "Kalm administator pushes kalm config to git")
Rel_U(kalmadmin, kalmvisualize, "Kalm administator visualizes kalm config")

Rel_U(enduser, kalmvisualize, "User with business need can visualize the automation lifecycle")
Rel_U(systemadmin, automation, "System administrator can execute playbooks")



Rel_D(cmdb, kalm, "Reads inventory from cmdb")
Rel_D(git, kalm, "Reads configuration from git")

Rel_D(kalm, automation, "updates automation engine configuration")
Rel_D(kalm, kalmvisualize, "updates kalm-visualize database")


@enduml
