
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


title   KALM system

Person(user, "Slutbruger", "Ansatte der bruger KALM.")
Enterprise_Boundary(c0, "Openknowit", "Openknowit organisation") {
System(ansible, "Ansible", "Server configuration management")
System(git, "Git", "Version control")
System(cmdb, "CMDB", "Configuration management database")

Enterprise_Boundary(c1, "Kalm", "automation og monitorering") {
    System(kalm, "KALM", "Knowit auitomation lifecycle management")
}
Enterprise_Boundary(c2, "Server ", "Virtuelle servere") {
    System(vmware, "wmware", "Virtual servers running on wmware")
    System(aws, "AWS", "Virtual servers running on AWS")
    System(azure, "Azure", "Virtual servers running on Azure")
}
}


Rel_U(git, ansible, "Read playbooks from git")
Rel_U(cmdb, ansible, "Read inventory from cmdb")

@enduml
