@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


title   KALM system


Enterprise_Boundary(c0, "My Company", "My awesome organisation") {

Person(kalmadmin, "Kalm system admin", "KALM system administrator")
Person(systemadmin, "System administrator", "OS system administrator")
Person(serviceadmin, "Service administrator", "administrator of services eg. zabbix, networker, etc")
Enterprise_Boundary(c2, "Server ", "Virtuelle servere") {
    System(vmware, "wmware", "Virtual servers running on wmware")
    System(physicalservers, "Physical", "Physical servers running on premise")
}

Enterprise_Boundary(c3, "Shared services", "Shared services in the organisation") {
    System(cmdb, "CMDB", "Configuration management database")
    System(automation, "Ansible", "Server configuration management")
    System(git, "Git", "Version control")
    System(incident, "Incident", "Incidentmamagement services")
}

Enterprise_Boundary(c1, "automation services", "Automation services") {
    System(kalm, "KALM", "Knowit auitomation lifecycle management")
}


}

Lay_L(serviceadmin, systemadmin)
Lay_R(serviceadmin, kalmadmin)




Rel_Neighbor(git, automation, "Read playbooks from git")
Rel_D(cmdb, automation, "Read inventory from cmdb")
Rel_U(automation, c2 , "execute playbooks on servers")


Rel_U(kalmadmin, git, "Kalm administator pushes kalm config to git")

Rel_U(systemadmin, automation, "System administrator can use automation services")
BiRel_R(systemadmin, git, "System administrator create and maintain repos in git")
BiRel_L(systemadmin, cmdb, "System administrator create and maintain servers in cmdb")
BiRel_D(serviceadmin, git, "Service administrator can use git for service configuration")





Rel_D(cmdb, kalm, "Reads inventory from cmdb")
Rel_D(git, kalm, "Reads configuration from git")

Rel_D(kalm, automation, "updates automation engine configuration")


@enduml
