
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_TOP_DOWN()
LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


title  Konceptuelt diagram over "Openknowit" systemet

Person(customer, "Slutbruger", "Ansatte der bruger KALM.")
Enterprise_Boundary(c0, "Openknowit", "Openknowit systemet") {
System(isilon, "Isilon", "Storage til data")
System(Hdrives, "H-drev", "Storage til data")
System(zabbix, "Zabbix", "Monitorering af systemer")
System(fileshare, "Fileshare", "Deling af datafiler")




Enterprise_Boundary(c1, "ignite", "ignnitesystemet") {
    System(ignitedb, "ignite DB", "Database med data til dashboards")
    System(igniteweb, "ignite WEB", "Brugervendte dashboards gui (grafana, django)")
    System(igniteapp, "ignite APP", "API til dashboards")
}
}
Rel_U(customer, igniteweb, "Bruger dashboards via")
Rel_D(isilon, fileshare, "sender data filer til")
Rel_D(Hdrives, fileshare, "sender data filer til")
Rel_U(fileshare, dashapp, "henter data fra")
Rel_Neighbor(zabbix, igniteapp, "sender monitoreringsdata til")
Rel_U(igniteapp, ignitedb, "gemmer data i")
Rel_D(ignitedb, igniteweb, "henter data fra")

@enduml
